### ISSUE TITLE
Link to executable is dead

### ISSUE THREAD

**Issue by lukapercic** [twome/pinguno#14]
**Describe the bug**
The link to windows executable in readme.md doesn't work

**To Reproduce**
1. Go to '[https://github.com/twome/pinguno/blob/master/releases/download/v0.2.0/pinguno-win.exe](https://github.com/twome/pinguno/blob/master/releases/download/v0.2.0/pinguno-win.exe)'

**Comment by twome** [comment]
Fixed, cheers. This is old and effectively abandoned so it'll probably break, sorry!
